version: '3.8'

services:
  mariadb-backup:
    build:
      context: .
      args:
        DB_HOST_ORIG: ${DB_HOST_ORIG}
        DB_PORT_ORIG: ${DB_PORT_ORIG}
        DB_USER_ORIG: ${DB_USER_ORIG}
        DB_PASS_ORIG: ${DB_PASS_ORIG}
        DB_NAME_ORIG: ${DB_NAME_ORIG}
        DB_HOST_DEST: ${DB_HOST_DEST}
        DB_PORT_DEST: ${DB_PORT_DEST}
        DB_USER_DEST: ${DB_USER_DEST}
        DB_PASS_DEST: ${DB_PASS_DEST}
        DB_NAME_DEST: ${DB_NAME_DEST}
    container_name: mariadb-backup
    env_file:
      - .env
    restart: unless-stopped
